## Step 1 - Adding Distribution QTY and Grouping

In [570]:
from importlib.metadata import Distribution
import pandas as pd

In [571]:
master_data = pd.read_excel("/Users/aswathshakthi/PycharmProjects/MLMR/MNP26/data/master-entry-all-2026-02-28.xlsx")
master_data = master_data[master_data["Quantity"]!=0].reset_index(drop=True)
master_data = master_data[master_data["Beneficiary Name"] != "Additional"]
master_data["Total Value"] = (master_data["Quantity"] * master_data["Cost Per Unit"]).round(2)
master_data = master_data.reset_index(drop=True)
master_data

,Application Number,Beneficiary Name,Requested Item,Quantity,Cost Per Unit,Total Value,Address,Mobile,Aadhar Number,Handicapped Status,Gender,Gender Category,Beneficiary Type,Item Type,Article Category,Super Category Article,Requested Item Tk,Comments
0,D051,Thanjavur,Konica Minolta Xerox machine,1,54800.0,54800.0,Thanjavur,94432 56395,NaN,NaN,NaN,NaN,District,Article,Electronics,Livelihood Aid,Konica Xerox Machine,NaN
1,D051,Thanjavur,Mantra L1 device,1,3200.0,3200.0,Thanjavur,94432 56395,NaN,NaN,NaN,NaN,District,Article,Computers & Printers,Infrastructure / Institutional Support Aid,Mantra L1 device,NaN
2,D051,Thanjavur,Foxin lamination machine,1,4000.0,4000.0,Thanjavur,94432 56395,NaN,NaN,NaN,NaN,District,Article,Computers & Printers,Livelihood Aid,Lamination machine,NaN
3,D051,Thanjavur,V-Guard System Table,1,12100.0,12100.0,Thanjavur,94432 56395,NaN,NaN,NaN,NaN,District,Article,Computers & Printers,Others,System Table,NaN
4,D051,Thanjavur,Education Aid,1,21500.0,21500.0,Thanjavur,94432 56395,NaN,NaN,NaN,NaN,District,Aid,Aid,Education Aid,Education Aid,Sathiyasri
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1268,I001,"Government Leprosy Centre,Chengalpattu.",Aluminium holed rice strainer with Handle,1,3500.0,3500.0,"Thirumani,Chengalpattu.",9943978134,NaN,NaN,NaN,NaN,Institutions,Article,Kitchen Items,Infrastructure / Institutional Support Aid,Holed Rice Strainer,NaN
1269,I001,"Government Leprosy Centre,Chengalpattu.",Preethi Mixie,1,3600.0,3600.0,"Thirumani,Chengalpattu.",9943978134,NaN,NaN,NaN,NaN,Institutions,Article,Electronics,Livelihood Aid,Preethi Mixie,NaN
1270,I001,"Government Leprosy Centre,Chengalpattu.",Cooker 20 Litres,1,5200.0,5200.0,"Thirumani,Chengalpattu.",9943978134,NaN,NaN,NaN,NaN,Institutions,Article,Kitchen Items,Infrastructure / Institutional Support Aid,Cooker 20 Litres,NaN
1271,I001,"Government Leprosy Centre,Chengalpattu.",Aluminium 10 Kg Dabara with Lid,1,5400.0,5400.0,"Thirumani,Chengalpattu.",9943978134,NaN,NaN,NaN,NaN,Institutions,Article,Kitchen Items,Infrastructure / Institutional Support Aid,Alu Dabara with lid,NaN
1272,P460,P.Manjula,Girls Cycle,1,4860.0,4860.0,Kesavarayanpettai\nMelmaruvathur,9629387083,9.605017e+11,No,Female,Married,Public,Article,Bicycle & Tricycle,Student Welfare Aid,Girls Cycle,NaN

In [572]:
print(master_data["Total Value"].sum())
print(master_data["Quantity"].sum())

38224647.97
4869

In [573]:
master_data.loc[master_data['Beneficiary Type'] != 'District', 'Names'] = master_data['Application Number'] + ' - ' + master_data['Beneficiary Name']
master_data.loc[master_data['Beneficiary Type'] == 'District', 'Names'] = master_data['Beneficiary Name']
# master_data = master_data.drop(columns=["Name"])

cols = list(master_data.columns)
cols.insert(1, cols.pop(cols.index('Names')))  # Move 'Concatenated' to second position
df = master_data[cols]
df

,Application Number,Names,Beneficiary Name,Requested Item,Quantity,Cost Per Unit,Total Value,Address,Mobile,Aadhar Number,Handicapped Status,Gender,Gender Category,Beneficiary Type,Item Type,Article Category,Super Category Article,Requested Item Tk,Comments
0,D051,Thanjavur,Thanjavur,Konica Minolta Xerox machine,1,54800.0,54800.0,Thanjavur,94432 56395,NaN,NaN,NaN,NaN,District,Article,Electronics,Livelihood Aid,Konica Xerox Machine,NaN
1,D051,Thanjavur,Thanjavur,Mantra L1 device,1,3200.0,3200.0,Thanjavur,94432 56395,NaN,NaN,NaN,NaN,District,Article,Computers & Printers,Infrastructure / Institutional Support Aid,Mantra L1 device,NaN
2,D051,Thanjavur,Thanjavur,Foxin lamination machine,1,4000.0,4000.0,Thanjavur,94432 56395,NaN,NaN,NaN,NaN,District,Article,Computers & Printers,Livelihood Aid,Lamination machine,NaN
3,D051,Thanjavur,Thanjavur,V-Guard System Table,1,12100.0,12100.0,Thanjavur,94432 56395,NaN,NaN,NaN,NaN,District,Article,Computers & Printers,Others,System Table,NaN
4,D051,Thanjavur,Thanjavur,Education Aid,1,21500.0,21500.0,Thanjavur,94432 56395,NaN,NaN,NaN,NaN,District,Aid,Aid,Education Aid,Education Aid,Sathiyasri
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1268,I001,"I001 - Government Leprosy Centre,Chengalpattu.","Government Leprosy Centre,Chengalpattu.",Aluminium holed rice strainer with Handle,1,3500.0,3500.0,"Thirumani,Chengalpattu.",9943978134,NaN,NaN,NaN,NaN,Institutions,Article,Kitchen Items,Infrastructure / Institutional Support Aid,Holed Rice Strainer,NaN
1269,I001,"I001 - Government Leprosy Centre,Chengalpattu.","Government Leprosy Centre,Chengalpattu.",Preethi Mixie,1,3600.0,3600.0,"Thirumani,Chengalpattu.",9943978134,NaN,NaN,NaN,NaN,Institutions,Article,Electronics,Livelihood Aid,Preethi Mixie,NaN
1270,I001,"I001 - Government Leprosy Centre,Chengalpattu.","Government Leprosy Centre,Chengalpattu.",Cooker 20 Litres,1,5200.0,5200.0,"Thirumani,Chengalpattu.",9943978134,NaN,NaN,NaN,NaN,Institutions,Article,Kitchen Items,Infrastructure / Institutional Support Aid,Cooker 20 Litres,NaN
1271,I001,"I001 - Government Leprosy Centre,Chengalpattu.","Government Leprosy Centre,Chengalpattu.",Aluminium 10 Kg Dabara with Lid,1,5400.0,5400.0,"Thirumani,Chengalpattu.",9943978134,NaN,NaN,NaN,NaN,Institutions,Article,Kitchen Items,Infrastructure / Institutional Support Aid,Alu Dabara with lid,NaN
1272,P460,P460 - P.Manjula,P.Manjula,Girls Cycle,1,4860.0,4860.0,Kesavarayanpettai\nMelmaruvathur,9629387083,9.605017e+11,No,Female,Married,Public,Article,Bicycle & Tricycle,Student Welfare Aid,Girls Cycle,NaN

In [574]:
df.isna().sum()
df["Aadhar Number"] = df["Aadhar Number"].fillna(0)
df["Handicapped Status"] = df["Handicapped Status"].fillna("NA")
df["Gender"] = df["Gender"].fillna("NA")
df["Gender Category"] = df["Gender Category"].fillna("NA")
df["Comments"] = df["Comments"].fillna("None")
df

,Application Number,Names,Beneficiary Name,Requested Item,Quantity,Cost Per Unit,Total Value,Address,Mobile,Aadhar Number,Handicapped Status,Gender,Gender Category,Beneficiary Type,Item Type,Article Category,Super Category Article,Requested Item Tk,Comments
0,D051,Thanjavur,Thanjavur,Konica Minolta Xerox machine,1,54800.0,54800.0,Thanjavur,94432 56395,0.000000e+00,NA,NA,NA,District,Article,Electronics,Livelihood Aid,Konica Xerox Machine,None
1,D051,Thanjavur,Thanjavur,Mantra L1 device,1,3200.0,3200.0,Thanjavur,94432 56395,0.000000e+00,NA,NA,NA,District,Article,Computers & Printers,Infrastructure / Institutional Support Aid,Mantra L1 device,None
2,D051,Thanjavur,Thanjavur,Foxin lamination machine,1,4000.0,4000.0,Thanjavur,94432 56395,0.000000e+00,NA,NA,NA,District,Article,Computers & Printers,Livelihood Aid,Lamination machine,None
3,D051,Thanjavur,Thanjavur,V-Guard System Table,1,12100.0,12100.0,Thanjavur,94432 56395,0.000000e+00,NA,NA,NA,District,Article,Computers & Printers,Others,System Table,None
4,D051,Thanjavur,Thanjavur,Education Aid,1,21500.0,21500.0,Thanjavur,94432 56395,0.000000e+00,NA,NA,NA,District,Aid,Aid,Education Aid,Education Aid,Sathiyasri
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1268,I001,"I001 - Government Leprosy Centre,Chengalpattu.","Government Leprosy Centre,Chengalpattu.",Aluminium holed rice strainer with Handle,1,3500.0,3500.0,"Thirumani,Chengalpattu.",9943978134,0.000000e+00,NA,NA,NA,Institutions,Article,Kitchen Items,Infrastructure / Institutional Support Aid,Holed Rice Strainer,None
1269,I001,"I001 - Government Leprosy Centre,Chengalpattu.","Government Leprosy Centre,Chengalpattu.",Preethi Mixie,1,3600.0,3600.0,"Thirumani,Chengalpattu.",9943978134,0.000000e+00,NA,NA,NA,Institutions,Article,Electronics,Livelihood Aid,Preethi Mixie,None
1270,I001,"I001 - Government Leprosy Centre,Chengalpattu.","Government Leprosy Centre,Chengalpattu.",Cooker 20 Litres,1,5200.0,5200.0,"Thirumani,Chengalpattu.",9943978134,0.000000e+00,NA,NA,NA,Institutions,Article,Kitchen Items,Infrastructure / Institutional Support Aid,Cooker 20 Litres,None
1271,I001,"I001 - Government Leprosy Centre,Chengalpattu.","Government Leprosy Centre,Chengalpattu.",Aluminium 10 Kg Dabara with Lid,1,5400.0,5400.0,"Thirumani,Chengalpattu.",9943978134,0.000000e+00,NA,NA,NA,Institutions,Article,Kitchen Items,Infrastructure / Institutional Support Aid,Alu Dabara with lid,None
1272,P460,P460 - P.Manjula,P.Manjula,Girls Cycle,1,4860.0,4860.0,Kesavarayanpettai\nMelmaruvathur,9629387083,9.605017e+11,No,Female,Married,Public,Article,Bicycle & Tricycle,Student Welfare Aid,Girls Cycle,None

In [575]:
group_cols = [
    'Application Number',
    'Names',
    'Beneficiary Name',
    'Requested Item',
    'Handicapped Status',
    'Gender',
    'Gender Category',
    'Beneficiary Type',
    'Item Type',
    'Article Category',
    'Super Category Article',
    'Requested Item Tk',
]

grouped = (
    df.groupby(group_cols, as_index=False)
      .agg({"Quantity": "sum", "Total Value": "sum"})
)
grouped

,Application Number,Names,Beneficiary Name,Requested Item,Handicapped Status,Gender,Gender Category,Beneficiary Type,Item Type,Article Category,Super Category Article,Requested Item Tk,Quantity,Total Value
0,D001,Andaman,Andaman,Bosch Electrician Kit 10 Re,NA,NA,NA,District,Article,Electricals,Livelihood Aid,Bosch Elec Kit 10 Re,1,4307.0
1,D001,Andaman,Andaman,Gp Welding Machine Arc 200,NA,NA,NA,District,Article,Electricals,Livelihood Aid,Gp Welding Arc 200,1,6726.0
2,D002,Ariyalur,Ariyalur,Agri Battery Sprayer,NA,NA,NA,District,Article,Agriculture,Agricultural Welfare Aid,Agri Battery Sprayer,8,33600.0
3,D002,Ariyalur,Ariyalur,Education Aid,NA,NA,NA,District,Aid,Aid,Education Aid,Education Aid,7,70000.0
4,D002,Ariyalur,Ariyalur,Iron Box Brass,NA,NA,NA,District,Article,Electronics,Livelihood Aid,Iron Box Brass,1,7500.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,P455,P455 - Karuppi,Karuppi,Ex Gratia Aid,No,Female,Widow,Public,Aid,Aid,Medical Aid,Ex Gratia Aid,1,100000.0
995,P456,P456 - S.Ranjith Singh,S.Ranjith Singh,Gents Cycle,No,Male,NA,Public,Article,Bicycle & Tricycle,Student Welfare Aid,Gents Cycle,1,5175.0
996,P457,P457 - S.Lathika,S.Lathika,Laptop,No,Female,Unmarried,Public,Article,Computers & Printers,Student Welfare Aid,Laptop,1,40000.0
997,P458,P458 - V.Raman,V.Raman,Ex Gratia Aid,No,Male,NA,Public,Aid,Aid,Medical Aid,Ex Gratia Aid,1,100000.0
998,P460,P460 - P.Manjula,P.Manjula,Girls Cycle,No,Female,Married,Public,Article,Bicycle & Tricycle,Student Welfare Aid,Girls Cycle,1,4860.0

In [576]:
grouped["Total Value"].sum()

38224647.97

In [577]:
grouped["Quantity"].sum()

4869

In [578]:
grouped[grouped[["Names","Requested Item"]].duplicated(keep=False)]

Empty DataFrame
Columns: [Application Number, Names, Beneficiary Name, Requested Item, Handicapped Status, Gender, Gender Category, Beneficiary Type, Item Type, Article Category, Super Category Article, Requested Item Tk, Quantity, Total Value]
Index: []

In [579]:
distribution_ls = pd.read_excel("/Users/aswathshakthi/PycharmProjects/MLMR/MNP26/data/seat-allocation-2026-02-28.xlsx")

distribution_ls = distribution_ls[["Application Number","Beneficiary Name","Requested Item","Quantity","Waiting Hall Quantity","Token Quantity"]]
distribution_ls

,Application Number,Beneficiary Name,Requested Item,Quantity,Waiting Hall Quantity,Token Quantity
0,D067,Additional,Dell laptop Core i5,1,1,0
1,D067,Additional,Digital Normal Banners and Foam Board,1,1,0
2,D067,Additional,Stationaries for MNP,1,1,0
3,D001,Andaman,Bosch Electrician Kit 10 Re,1,0,1
4,D001,Andaman,Gp Welding Machine Arc 200,1,0,1
...,...,...,...,...,...,...
997,D065,Virudhunagar,Sewing Machine ORD + Motor(1/20),23,23,0
998,D066,Visakapattinam,Laptop,1,0,1
999,D066,Visakapattinam,Sewing Machine ORD,2,2,0
1000,I001,"Government Leprosy Centre,Chengalpattu.",Aluminium 10 Kg Dabara with Lid,1,1,0
1001,P460,P.Manjula,Girls Cycle,1,0,1

## Step 2&3 : Sequence List

In [580]:
step2 = grouped.merge(distribution_ls, on=["Application Number","Beneficiary Name","Requested Item","Quantity"],how="left")
step2

,Application Number,Names,Beneficiary Name,Requested Item,Handicapped Status,Gender,Gender Category,Beneficiary Type,Item Type,Article Category,Super Category Article,Requested Item Tk,Quantity,Total Value,Waiting Hall Quantity,Token Quantity
0,D001,Andaman,Andaman,Bosch Electrician Kit 10 Re,NA,NA,NA,District,Article,Electricals,Livelihood Aid,Bosch Elec Kit 10 Re,1,4307.0,0,1
1,D001,Andaman,Andaman,Gp Welding Machine Arc 200,NA,NA,NA,District,Article,Electricals,Livelihood Aid,Gp Welding Arc 200,1,6726.0,0,1
2,D002,Ariyalur,Ariyalur,Agri Battery Sprayer,NA,NA,NA,District,Article,Agriculture,Agricultural Welfare Aid,Agri Battery Sprayer,8,33600.0,8,0
3,D002,Ariyalur,Ariyalur,Education Aid,NA,NA,NA,District,Aid,Aid,Education Aid,Education Aid,7,70000.0,6,1
4,D002,Ariyalur,Ariyalur,Iron Box Brass,NA,NA,NA,District,Article,Electronics,Livelihood Aid,Iron Box Brass,1,7500.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,P455,P455 - Karuppi,Karuppi,Ex Gratia Aid,No,Female,Widow,Public,Aid,Aid,Medical Aid,Ex Gratia Aid,1,100000.0,0,1
995,P456,P456 - S.Ranjith Singh,S.Ranjith Singh,Gents Cycle,No,Male,NA,Public,Article,Bicycle & Tricycle,Student Welfare Aid,Gents Cycle,1,5175.0,0,1
996,P457,P457 - S.Lathika,S.Lathika,Laptop,No,Female,Unmarried,Public,Article,Computers & Printers,Student Welfare Aid,Laptop,1,40000.0,0,1
997,P458,P458 - V.Raman,V.Raman,Ex Gratia Aid,No,Male,NA,Public,Aid,Aid,Medical Aid,Ex Gratia Aid,1,100000.0,0,1
998,P460,P460 - P.Manjula,P.Manjula,Girls Cycle,No,Female,Married,Public,Article,Bicycle & Tricycle,Student Welfare Aid,Girls Cycle,1,4860.0,0,1

In [581]:
print(step2["Waiting Hall Quantity"].notna().sum())
print(step2[step2["Beneficiary Type"]=="District"]["Waiting Hall Quantity"].isna().sum())
print(step2["Total Value"].sum())
print(step2["Waiting Hall Quantity"].sum())
print(step2["Token Quantity"].sum())

999
0
38224647.97
3610
1259

In [582]:
## Waiting hall qty + token quantity = Quantity ---> Calcualtion
def check_quantity_balance(
    df: pd.DataFrame,
    qty_col: str = "Quantity",
    waiting_col: str = "Waiting Hall Quantity",
    token_col: str = "Token Quantity",
    fillna_zero: bool = True):
    d = df.copy()

    if fillna_zero:
        d[[qty_col, waiting_col, token_col]] = d[[qty_col, waiting_col, token_col]].fillna(0)

    d["Calculated Quantity"] = d[waiting_col] + d[token_col]
    d["Quantity Match"] = d[qty_col] == d["Calculated Quantity"]
    d["Difference"] = d[qty_col] - d["Calculated Quantity"]

    mismatches = d[~d["Quantity Match"]].copy()

    summary = {
        "total_rows": len(d),
        "matched_rows": int(d["Quantity Match"].sum()),
        "mismatched_rows": int((~d["Quantity Match"]).sum()),
    }

    return summary, mismatches, d
summary, mismatches, checked_df = check_quantity_balance(step2)
print(summary)
mismatches.head()

{'total_rows': 999, 'matched_rows': 999, 'mismatched_rows': 0}

Empty DataFrame
Columns: [Application Number, Names, Beneficiary Name, Requested Item, Handicapped Status, Gender, Gender Category, Beneficiary Type, Item Type, Article Category, Super Category Article, Requested Item Tk, Quantity, Total Value, Waiting Hall Quantity, Token Quantity, Calculated Quantity, Quantity Match, Difference]
Index: []

In [583]:
seq = pd.read_excel("/Users/aswathshakthi/PycharmProjects/MLMR/MNP26/data/sequence-list-2026-02-28.xlsx")
seq

     Sequence No                         Requested Item
0              1                             Cow & Calf
1              2                           Goat(1 Pair)
2              3                          Plant Sapling
3              4                          Free Marriage
4              5      Kirolskar Min T8 Dlx Power Weeder
..           ...                                    ...
119          120                  Steel Cupboard 6 1/2'
120          121      Steel cupboard Glass Book Shelf
121          122                            Ceiling Fan
122          123  Digital Normal Banners and Foam Board
123          124                   Stationaries for MNP

[124 rows x 2 columns]

In [584]:
step3 = step2.merge(seq, on="Requested Item", how="left").reset_index(drop=True)
step3

,Application Number,Names,Beneficiary Name,Requested Item,Handicapped Status,Gender,Gender Category,Beneficiary Type,Item Type,Article Category,Super Category Article,Requested Item Tk,Quantity,Total Value,Waiting Hall Quantity,Token Quantity,Sequence No
0,D001,Andaman,Andaman,Bosch Electrician Kit 10 Re,NA,NA,NA,District,Article,Electricals,Livelihood Aid,Bosch Elec Kit 10 Re,1,4307.0,0,1,49
1,D001,Andaman,Andaman,Gp Welding Machine Arc 200,NA,NA,NA,District,Article,Electricals,Livelihood Aid,Gp Welding Arc 200,1,6726.0,0,1,53
2,D002,Ariyalur,Ariyalur,Agri Battery Sprayer,NA,NA,NA,District,Article,Agriculture,Agricultural Welfare Aid,Agri Battery Sprayer,8,33600.0,8,0,43
3,D002,Ariyalur,Ariyalur,Education Aid,NA,NA,NA,District,Aid,Aid,Education Aid,Education Aid,7,70000.0,6,1,33
4,D002,Ariyalur,Ariyalur,Iron Box Brass,NA,NA,NA,District,Article,Electronics,Livelihood Aid,Iron Box Brass,1,7500.0,1,0,55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,P455,P455 - Karuppi,Karuppi,Ex Gratia Aid,No,Female,Widow,Public,Aid,Aid,Medical Aid,Ex Gratia Aid,1,100000.0,0,1,31
995,P456,P456 - S.Ranjith Singh,S.Ranjith Singh,Gents Cycle,No,Male,NA,Public,Article,Bicycle & Tricycle,Student Welfare Aid,Gents Cycle,1,5175.0,0,1,94
996,P457,P457 - S.Lathika,S.Lathika,Laptop,No,Female,Unmarried,Public,Article,Computers & Printers,Student Welfare Aid,Laptop,1,40000.0,0,1,22
997,P458,P458 - V.Raman,V.Raman,Ex Gratia Aid,No,Male,NA,Public,Aid,Aid,Medical Aid,Ex Gratia Aid,1,100000.0,0,1,31
998,P460,P460 - P.Manjula,P.Manjula,Girls Cycle,No,Female,Married,Public,Article,Bicycle & Tricycle,Student Welfare Aid,Girls Cycle,1,4860.0,0,1,95

In [585]:
print(step3["Waiting Hall Quantity"].notna().sum())
print(step3[step3["Beneficiary Type"]=="District"]["Waiting Hall Quantity"].isna().sum())
print(step3["Total Value"].sum())
print(step3["Waiting Hall Quantity"].sum())
print(step3["Token Quantity"].sum())
print(step3["Sequence No"].isna().sum())

999
0
38224647.97
3610
1259
0

In [586]:
step3.isna().sum()

Application Number        0
Names                     0
Beneficiary Name          0
Requested Item            0
Handicapped Status        0
Gender                    0
Gender Category           0
Beneficiary Type          0
Item Type                 0
Article Category          0
Super Category Article    0
Requested Item Tk         0
Quantity                  0
Total Value               0
Waiting Hall Quantity     0
Token Quantity            0
Sequence No               0
dtype: int64

In [587]:
step3["R_Names"]=""
step3.loc[step3['Beneficiary Type'] != 'Public', 'R_Names'] = step3["Beneficiary Name"]
step3.loc[step3['Beneficiary Type'] == 'Public', 'R_Names'] = "AA_Public"
step3.loc[step3['Beneficiary Type'] == 'Institutions', 'R_Names'] = "A_Institutions"

step3

,Application Number,Names,Beneficiary Name,Requested Item,Handicapped Status,Gender,Gender Category,Beneficiary Type,Item Type,Article Category,Super Category Article,Requested Item Tk,Quantity,Total Value,Waiting Hall Quantity,Token Quantity,Sequence No,R_Names
0,D001,Andaman,Andaman,Bosch Electrician Kit 10 Re,NA,NA,NA,District,Article,Electricals,Livelihood Aid,Bosch Elec Kit 10 Re,1,4307.0,0,1,49,Andaman
1,D001,Andaman,Andaman,Gp Welding Machine Arc 200,NA,NA,NA,District,Article,Electricals,Livelihood Aid,Gp Welding Arc 200,1,6726.0,0,1,53,Andaman
2,D002,Ariyalur,Ariyalur,Agri Battery Sprayer,NA,NA,NA,District,Article,Agriculture,Agricultural Welfare Aid,Agri Battery Sprayer,8,33600.0,8,0,43,Ariyalur
3,D002,Ariyalur,Ariyalur,Education Aid,NA,NA,NA,District,Aid,Aid,Education Aid,Education Aid,7,70000.0,6,1,33,Ariyalur
4,D002,Ariyalur,Ariyalur,Iron Box Brass,NA,NA,NA,District,Article,Electronics,Livelihood Aid,Iron Box Brass,1,7500.0,1,0,55,Ariyalur
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,P455,P455 - Karuppi,Karuppi,Ex Gratia Aid,No,Female,Widow,Public,Aid,Aid,Medical Aid,Ex Gratia Aid,1,100000.0,0,1,31,AA_Public
995,P456,P456 - S.Ranjith Singh,S.Ranjith Singh,Gents Cycle,No,Male,NA,Public,Article,Bicycle & Tricycle,Student Welfare Aid,Gents Cycle,1,5175.0,0,1,94,AA_Public
996,P457,P457 - S.Lathika,S.Lathika,Laptop,No,Female,Unmarried,Public,Article,Computers & Printers,Student Welfare Aid,Laptop,1,40000.0,0,1,22,AA_Public
997,P458,P458 - V.Raman,V.Raman,Ex Gratia Aid,No,Male,NA,Public,Aid,Aid,Medical Aid,Ex Gratia Aid,1,100000.0,0,1,31,AA_Public
998,P460,P460 - P.Manjula,P.Manjula,Girls Cycle,No,Female,Married,Public,Article,Bicycle & Tricycle,Student Welfare Aid,Girls Cycle,1,4860.0,0,1,95,AA_Public

In [588]:
step3.to_excel("/Users/aswathshakthi/PycharmProjects/MLMR/MNP26/Result/1_Master_Records_Seat_Seq.xlsx",index=False)